version: '3'
services:

  # db:
  #   image: "mysql:8"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: "1"
  #     MYSQL_DATABASE: "${DB_DATABASE}"
  #     MYSQL_USER: "${DB_USERNAME}"
  #     MYSQL_PASSWORD: "${DB_PASSWORD}"
  #   volumes:
  #     - db_data:/var/lib/mysql
  #   env_file:
  #     - ".env"

  # redis:
  #   image: "redis:alpine"

  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    # ports:
    #   - "${APP_HOST}:${APP_PORT}:80"
    # env_file:
    #   - ".env"
    # links:
    #   - db
    #   - redis

# volumes:
#   db_data: {}
